## Лабораторная работа № 2

Сафронова Мария

Группа Т12О-101М

In [10]:
import numpy as np

#### Перемножить матрицы 5x3 и 3x2

In [11]:
np.dot(np.arange(15).reshape((5, 3)), np.arange(6).reshape((3, 2)))

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [20]:
arr = np.arange(11)
arr[(arr >= 3) & (arr <= 8)] *= -1
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### Создать 5x5 матрицу со значениями в строках от 0 до 4

In [21]:
np.array(list(range(5))*5).reshape((5, 5))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### Есть генератор, сделать с его помощью массив

In [28]:
def gen():
    for i in range(10):
        yield i

np.fromiter(gen(), dtype=np.int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [32]:
np.linspace(0, 1, 11, endpoint=False)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182])

#### Отсортировать вектор

In [42]:
arr = np.random.random(5)
arr.sort()
arr

array([0.17401269, 0.45188404, 0.53143195, 0.78397556, 0.82565884])

#### Проверить, одинаковы ли 2 numpy массива

In [40]:
a = np.array([4, 3, 9])
b = np.array([2, 5, 5])
np.array_equal(a, b)

False

#### Сделать массив неизменяемым

In [18]:
a = np.arange(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

#### Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [56]:
coord = np.random.random((10, 2))

x, y = coord[:,0], coord[:,1]

radius = np.hypot(x, y)
angle = np.arctan2(y, x)

np.array([radius, angle])

array([[0.79940316, 0.7651712 , 0.73235708, 0.57785499, 0.92273095,
        0.97775457, 0.42779867, 0.98364419, 0.79871724, 0.58481193],
       [0.4819755 , 1.4475597 , 0.79678286, 0.68564272, 1.43630341,
        0.81719447, 1.08794332, 0.8482966 , 1.55122312, 0.5823655 ]])

#### Заменить максимальный элемент на ноль

In [57]:
arr = np.arange(10)
arr[arr.argmax()] = 0
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0])

#### Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [78]:
m = np.zeros([2,3], [('x', int), ('y', int)])
m['x'], m['y'] = np.meshgrid(np.linspace(0,1,3), np.linspace(0,1,2))
m

array([[(0, 0), (0, 0), (1, 0)],
       [(0, 1), (0, 1), (1, 1)]], dtype=[('x', '<i4'), ('y', '<i4')])

#### Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [79]:
x = np.arange(1, 10)
y = np.random.randint(20, 30, size=10)

C = 1 / (x.reshape((-1, 1)) - y)
C

array([[-0.04      , -0.04      , -0.04      , -0.05      , -0.03846154,
        -0.04545455, -0.04      , -0.04761905, -0.04545455, -0.04545455],
       [-0.04166667, -0.04166667, -0.04166667, -0.05263158, -0.04      ,
        -0.04761905, -0.04166667, -0.05      , -0.04761905, -0.04761905],
       [-0.04347826, -0.04347826, -0.04347826, -0.05555556, -0.04166667,
        -0.05      , -0.04347826, -0.05263158, -0.05      , -0.05      ],
       [-0.04545455, -0.04545455, -0.04545455, -0.05882353, -0.04347826,
        -0.05263158, -0.04545455, -0.05555556, -0.05263158, -0.05263158],
       [-0.04761905, -0.04761905, -0.04761905, -0.0625    , -0.04545455,
        -0.05555556, -0.04761905, -0.05882353, -0.05555556, -0.05555556],
       [-0.05      , -0.05      , -0.05      , -0.06666667, -0.04761905,
        -0.05882353, -0.05      , -0.0625    , -0.05882353, -0.05882353],
       [-0.05263158, -0.05263158, -0.05263158, -0.07142857, -0.05      ,
        -0.0625    , -0.05263158, -0.06666667

#### Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [87]:
for dtype in [np.int8, np.int32, np.int64]:
   print(dtype, np.iinfo(dtype).min, np.iinfo(dtype).max)  
for dtype in [np.float32, np.float64]:
   print(dtype, np.finfo(dtype).min, np.finfo(dtype).max)  


<class 'numpy.int8'> -128 127
<class 'numpy.int32'> -2147483648 2147483647
<class 'numpy.int64'> -9223372036854775808 9223372036854775807
<class 'numpy.float32'> -3.4028235e+38 3.4028235e+38
<class 'numpy.float64'> -1.7976931348623157e+308 1.7976931348623157e+308


#### Напечатать все значения в массиве

In [94]:
arr = np.arange(10)
print(arr)

for i in arr:
    print(i, end=' ')

[0 1 2 3 4 5 6 7 8 9]
0 1 2 3 4 5 6 7 8 9 

#### Найти ближайшее к заданному значению число в заданном массиве

In [96]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 10])

def find_nearest(array: np.ndarray, value):
    idx = (np.abs(array - value)).argmin()
    return array[idx]

find_nearest(arr, 8)

7

#### Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

In [100]:
np.zeros(10, dtype=[('x', np.int), ('y', np.int), ('color', np.uint, (3,))])

array([(0, 0, [0, 0, 0]), (0, 0, [0, 0, 0]), (0, 0, [0, 0, 0]),
       (0, 0, [0, 0, 0]), (0, 0, [0, 0, 0]), (0, 0, [0, 0, 0]),
       (0, 0, [0, 0, 0]), (0, 0, [0, 0, 0]), (0, 0, [0, 0, 0]),
       (0, 0, [0, 0, 0])],
      dtype=[('x', '<i4'), ('y', '<i4'), ('color', '<u4', (3,))])

#### Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

In [122]:
from scipy.spatial import distance_matrix
 
m = np.random.randint(low=0, high=100, size=[3,2])
print(m)
print()

dist_m = distance_matrix(m, m)
print(dist_m)

[[61  8]
 [10 28]
 [47 51]]

[[ 0.         54.7813837  45.22167622]
 [54.7813837   0.         43.56604182]
 [45.22167622 43.56604182  0.        ]]


#### Преобразовать массив из float в int

In [125]:
(np.random.random(size=5) + 1).astype(np.int)

array([1, 1, 1, 1, 1])

#### Дан файл:
```csv
1,2,3,4,5
6,,,7,8
,,9,10,11
```
Как прочитать его?

In [116]:
with open('./tmp.txt', 'w') as f:
    f.write("1,2,3,4,5\n6,,,7,8\n,,9,10,11")

np.genfromtxt('./tmp.txt', delimiter=',')

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### Каков эквивалент функции enumerate для numpy массивов?

In [127]:
list(np.ndenumerate(np.arange(5)))

[((0,), 0), ((1,), 1), ((2,), 2), ((3,), 3), ((4,), 4)]

#### Сформировать 2D массив с распределением Гаусса

In [128]:
np.random.normal(size=(2, 2))

array([[ 0.06716035, -0.51196038],
       [-0.57167606,  0.23250708]])

#### Случайно расположить p элементов в 2D массив

In [132]:
p = 3 
m = np.zeros((4, 4))
np.put(m, np.random.choice(range(m.size), p, replace=False), 7)
print(m)

[[7. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 7. 0.]
 [0. 0. 0. 7.]]


#### Отнять среднее из каждой строки в матрице

In [106]:
matrix = np.arange(25).reshape(5, 5)
matrix - matrix.mean(axis=1, keepdims=True)

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

#### Отсортировать матрицу по n-ому столбцу

In [107]:
N = 3
matrix = np.arange(25).reshape(5, 5)[::-1]

matrix[matrix[:,N].argsort()]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### Определить, есть ли в 2D массиве нулевые столбцы

In [108]:
arr = np.random.randint(0,3,(3,10))
np.all((arr == 0), axis=1)

array([False, False, False])

#### Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [133]:
arr = np.ones(10)
print('array' ,arr)
ind = np.random.randint(0, len(arr), 20)
print('индексы', ind)
arr += np.bincount(ind, minlength=len(arr))
arr

array [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
индексы [1 0 4 4 4 1 5 4 9 0 2 6 9 8 7 1 3 3 2 9]


array([3., 4., 3., 3., 5., 2., 2., 2., 2., 4.])

#### Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [138]:
width, height = 4, 4

pixels = np.random.randint(0, 2, (height, width, 3)).astype(np.ubyte)

vec = pixel_colors.reshape((height*width, 3))
print(vec)
unique = np.unique(pixel_colors_as_vector, axis=0)

len(unique)

[[1 0 0]
 [0 1 1]
 [0 0 0]
 [0 1 1]
 [0 0 0]
 [1 1 0]
 [1 0 0]
 [1 1 1]
 [1 1 0]
 [1 0 0]
 [1 0 1]
 [1 0 0]
 [1 0 1]
 [0 0 0]
 [0 0 0]
 [0 1 0]]


7

#### Дан четырехмерный массив, посчитать сумму по последним двум осям

In [115]:
a = np.random.randint(0,10, (3,3,3,3))

a.reshape(arr.shape[:-2] + (-1,)).sum(axis=-1)

array([[45, 39, 35],
       [31, 29, 52],
       [45, 41, 35]])

#### Найти диагональные элементы произведения матриц

In [112]:
m1 = np.random.random((3, 5))
m2 = np.random.random((5, 3))

np.diag(np.dot(m1, m2))

array([0.84573144, 1.65454677, 2.02598289])