**Лабораторная работа № 1**

Сафронова Мария, Т12О-101М


**Импортировать `numpy` под именем `np`**

In [2]:
import numpy as np

**Напечатать версию и конфигурацию**

In [3]:
np.version.full_version

'1.16.5'

In [4]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/User/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/User

**Создать вектор (одномерный массив) размера 10, заполненный нулями**

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Создать вектор размера 10, заполненный единицами**

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Создать вектор размера 10, заполненный числом 2.5**

In [6]:
np.full((10,), 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

**Как получить документацию о функции numpy.add из командной строки**

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

**Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1**

In [7]:
v = np.zeros(10)
v[4] = 1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Создать вектор со значениями от 10 до 49

In [9]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Развернуть вектор (первый становится последним)

In [10]:
vec = np.arange(5)
np.flip(vec, 0)

array([4, 3, 2, 1, 0])

#### Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [11]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [12]:
v = np.array([1, 2, 0, 0, 4, 0])
v.nonzero()

(array([0, 1, 4]),)

#### Создать массив 3x3x3 со случайными значениями

In [8]:
np.random.randint(3*3*3, size=(3, 3, 3))

array([[[ 8, 22,  0],
        [12, 25, 23],
        [21, 24, 14]],

       [[ 9, 26,  0],
        [24,  3, 19],
        [ 9, 24,  6]],

       [[ 9, 22, 11],
        [15,  0, 26],
        [24,  1,  2]]])

#### Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [9]:
v = np.random.randint(10*10, size=(10, 10))
v.min(), v.max()

(0, 99)

#### Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [10]:
v = np.random.randint(30, size=(30,))
np.average(v), v.mean()

(12.366666666666667, 12.366666666666667)

#### Создать матрицу с 0 внутри, и 1 на границах

In [11]:
v = np.ones((5, 5))
v[1:-1,1:-1] = 0
v

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Выяснить результат следующих выражений
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
```

In [12]:
0 * np.nan

nan

In [13]:
np.nan == np.nan

False

In [14]:
np.inf > np.nan

False

In [15]:
np.nan - np.nan

nan

#### Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [21]:
v = np.zeros((5, 5))
np.fill_diagonal(v[1:], val=[1, 2, 3, 4])
v

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### Создать 8x8 матрицу и заполнить её в шахматном порядке

In [22]:
v = np.zeros((8, 8))
v[1::2,::2] = 1
v[::2, 1::2] = 1
v

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [16]:
v = np.arange(6*7*8).reshape((6, 7, 8))
v[np.unravel_index(100, (6, 7, 8))]

100

#### Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [24]:
tile_item = np.array([0, 1, 1, 0]).reshape((2, 2))
np.tile(tile_item, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])