## Лабораторная работа № 3

Сафронова Мария

Группа Т12О-101М

In [7]:
import numpy as np

#### Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [33]:
vec = np.arange(1, 6)
nVec = np.zeros(len(vec) + (len(vec)-1)*3)
nVec[::4] = vec
nVec

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### Поменять 2 строки в матрице

In [17]:
matr = np.arange(9).reshape(3,3)
print(matr)
matr[[1,2]] = arr[[2,1]]
matr

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники

In [43]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 38) ( 0, 47) ( 1,  5) ( 1, 82) ( 4, 13) ( 4, 33) ( 5, 82) ( 6, 22)
 ( 6, 34) ( 6, 42) ( 6, 52) (10, 82) (10, 93) (13, 33) (19, 74) (19, 94)
 (22, 52) (34, 42) (38, 47) (40, 62) (40, 73) (48, 79) (48, 94) (58, 97)
 (58, 99) (62, 73) (74, 94) (79, 94) (82, 93) (97, 99)]


#### Дан массив C; создать массив A, что np.bincount(A) == C

In [58]:
C = np.bincount([0,0,2,2,8,8])
print(C)
np.repeat(np.arange(len(C)), C)


[2 0 2 0 0 0 0 0 2]


array([0, 0, 2, 2, 8, 8])

#### Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))

In [61]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

rolling(np.arange(10), 3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### Инвертировать булево значение, или поменять знак у числового массива без создания нового

In [75]:
Z = np.random.randint(0,2,5)
print(Z)
np.logical_not(Z, out=Z)

[0 1 0 0 0]


array([1, 0, 1, 1, 1])

In [74]:
Z = np.random.uniform(-1.0,1.0,5)
print(Z)
np.negative(Z, out=Z)

[ 0.46262875 -0.13487002 -0.84949118 -0.90683165  0.97257965]


array([-0.46262875,  0.13487002,  0.84949118,  0.90683165, -0.97257965])

#### Посчитать ранг матрицы

In [76]:
Z = np.random.uniform(0,1,(10,10))
np.linalg.matrix_rank(Z)

10

#### Найти наиболее частое значение в массиве

In [77]:
Z = np.random.randint(0,10,50)
np.bincount(Z).argmax()

2

#### Извлечь все смежные 3x3 блоки из 10x10 матрицы

In [80]:
from numpy.lib import stride_tricks

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 1 0]
   [2 3 0]
   [2 0 1]]

  [[1 0 2]
   [3 0 0]
   [0 1 3]]

  [[0 2 4]
   [0 0 2]
   [1 3 3]]

  [[2 4 1]
   [0 2 3]
   [3 3 0]]

  [[4 1 2]
   [2 3 3]
   [3 0 2]]

  [[1 2 0]
   [3 3 3]
   [0 2 3]]

  [[2 0 4]
   [3 3 3]
   [2 3 1]]

  [[0 4 1]
   [3 3 1]
   [3 1 0]]]


 [[[2 3 0]
   [2 0 1]
   [3 4 3]]

  [[3 0 0]
   [0 1 3]
   [4 3 0]]

  [[0 0 2]
   [1 3 3]
   [3 0 1]]

  [[0 2 3]
   [3 3 0]
   [0 1 2]]

  [[2 3 3]
   [3 0 2]
   [1 2 3]]

  [[3 3 3]
   [0 2 3]
   [2 3 2]]

  [[3 3 3]
   [2 3 1]
   [3 2 2]]

  [[3 3 1]
   [3 1 0]
   [2 2 0]]]


 [[[2 0 1]
   [3 4 3]
   [3 4 0]]

  [[0 1 3]
   [4 3 0]
   [4 0 4]]

  [[1 3 3]
   [3 0 1]
   [0 4 0]]

  [[3 3 0]
   [0 1 2]
   [4 0 3]]

  [[3 0 2]
   [1 2 3]
   [0 3 2]]

  [[0 2 3]
   [2 3 2]
   [3 2 3]]

  [[2 3 1]
   [3 2 2]
   [2 3 1]]

  [[3 1 0]
   [2 2 0]
   [3 1 1]]]


 [[[3 4 3]
   [3 4 0]
   [1 4 0]]

  [[4 3 0]
   [4 0 4]
   [4 0 4]]

  [[3 0 1]
   [0 4 0]
   [0 4 3]]

  [[0 1 2]
   [4 0 3]
   [4 3 4]]

  [[1 2 3]
   

#### Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

In [82]:
p, n = 5, 4
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
S

array([[20.],
       [20.],
       [20.],
       [20.]])

#### Дан массив 16x16, посчитать сумму по блокам 4x4

In [83]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(
    np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
    np.arange(0, Z.shape[1], k),
    axis=1,
)
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### Найти n наибольших значений в массиве

In [85]:
Z = np.arange(100)
np.random.shuffle(Z)
n = 5

print(Z[np.argpartition(-Z,n)[:n]])

[98 99 97 96 95]


#### Построить прямое произведение массивов (все комбинации с каждым элементом)

In [86]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [88]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 3 4 5 7]


#### Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

In [89]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[1 3 4]
 [1 1 0]
 [1 4 2]
 [0 3 2]
 [3 1 1]
 [1 4 0]
 [4 0 0]
 [2 1 2]
 [1 1 4]
 [3 4 4]]
[[1 3 4]
 [1 1 0]
 [1 4 2]
 [0 3 2]
 [3 1 1]
 [1 4 0]
 [4 0 0]
 [2 1 2]
 [1 1 4]
 [3 4 4]]


#### Преобразовать вектор чисел в матрицу бинарных представлений

In [90]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### Дан двумерный массив. Найти все различные строки

In [91]:
Z = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [1 0 0]
 [1 1 1]]


#### Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

In [87]:
A = np.random.random((10,))
B = np.random.random((10,))

np.einsum('i->', A)       # sum(A)

5.180720713949768

In [ ]:
np.einsum('i,i->i', A, B) # A * B

In [ ]:
np.einsum('i,i', A, B)    # np.inner(A, B)

In [ ]:
np.einsum('i,j', A, B)    # np.outer(A, B)