## Лабораторная работа № 6

Сафронова Мария

Группа Т12О-101М

In [4]:
import numpy as np
import pandas as pd

 #### Найти евклидово расстояние между двумя объектами Series

In [8]:
a = pd.Series([1, 3, 5, 7]) 
b = pd.Series([2, 4, 6, 8]) 

np.linalg.norm(a-b)

2.0

#### Найти индексы локальных максимумов в объекте Series

In [26]:
s = pd.Series([3, 1, 12, 8, 16, 4, 7])

print(np.diff(s))
print(np.sign(np.diff(s)))

discrete_difference = np.diff(np.sign(np.diff(s)))

print(discrete_difference)

np.where(discrete_difference == -2)[0] + 1


[ -2  11  -4   8 -12   3]
[-1  1 -1  1 -1  1]
[ 2 -2  2 -2  2]


array([2, 4], dtype=int64)

#### Заменить пробелы наименее часто встречающимся символом

In [31]:
s = pd.Series(list('q ww eee'))

cnt = s.value_counts()
m = cnt.index[-1]

rez = s.replace(' ', m)
''.join(rez)

'qqwwqeee'

#### Создать объект Series, который содержит в индексах даты выходных дней субботы, а в значениях случайные числа от 1 до 10

In [35]:
pd.Series(np.random.randint(low=1,high=10,size=[10]), pd.date_range('2020-11-28', periods=10, freq='W-SAT'))

2020-11-28    3
2020-12-05    8
2020-12-12    7
2020-12-19    4
2020-12-26    7
2021-01-02    4
2021-01-09    2
2021-01-16    7
2021-01-23    3
2021-01-30    6
Freq: W-SAT, dtype: int32

#### Заполнить пропущенные даты, значением выше (заполненной даты)

In [39]:
sample = pd.Series(pd.date_range('2020-11-28', periods=4, freq='D'))
sample.ffill() #forward fill

0   2020-11-28
1   2020-11-29
2   2020-11-30
3   2020-12-01
dtype: datetime64[ns]

#### Вычислить автокорреляцию объекта Series

In [40]:
pd.Series(np.arange(5)).autocorr()

1.0